### ISSUE TITLE
Plugging database

### ISSUE THREAD

**Issue by bcodus** [bnkamalesh/webgo#35]
Hello, I'm wondering how can I plug sqlx in order to use MySQL database. A sample code would be very appreciated.

**Comment by bnkamalesh** [comment]
@bcodus since webgo is a microframework. There's no specific way of using a DB driver, or ORM etc. It only deals with handling HTTP requests, middleware capability etc.

Though you can refer [goapp for sample on how to use a DB, cache etc.](https://github.com/bnkamalesh/goapp/)
