### ISSUE TITLE
feat: HTTP cache implementation.

### ISSUE THREAD

**Issue by darkweak** [bnkamalesh/webgo#37]
**Is your feature request related to a problem? Please describe.**
An HTTP cache system would be great in webgo to avoid the execution of unchanged response.

**Describe the solution you'd like**
I can implement [Souin](https://github.com/darkweak/souin) as the HTTP cache middleware. With that it will support the CDN validation/invalidation too, set default cache-control header, store in a distributed system using olric or in memory with badger. 

**Describe alternatives you've considered**

**Additional context**
It's already available as Træfik/Tyk plugin, skipper/gin/echo middleware, and is used in the official caddy cache-handler.

Cheers ✌️

**Comment by bnkamalesh** [comment]
@darkweak that sounds awesome. I'm open to PRs, looks like it can be easily implemented as a middleware.

**Comment by darkweak** [comment]
@bnkamalesh I'm ready to merge on my side. If the integration looks good to you we can probably integrate it inside webgo directly.

Cheers ✌️
