### ISSUE TITLE
optional parameters

### ISSUE THREAD

**Issue by mybigman** [bnkamalesh/webgo#45]
**Is your feature request related to a problem? Please describe.**
Unable to use optional parameters

**Describe the solution you'd like**
To have the ability to use optional parameters that would allow the use of `/user` or `/user/1`

**Additional context**
```go
// something like
Pattern: "/user/:id?"
```

**Comment by bnkamalesh** [comment]
Interesting, though this can be setup by configuring 2 different routes. One with the URI parameter and another with no URI parameter in the route pattern.

**Comment by mybigman** [comment]
yeh i figured that would be the response. All good, just thought it might be handy.

**Comment by bnkamalesh** [comment]
@mybigman thank you for the suggestion nonetheless. Also, making the URI parameter optional isn't as straight forward as it looks either. For instance, if you have a URI which looks like this

> /users/:userID?/notes`

Should `/users//notes` be considered a valid URI? Or is this meant only for parameters at the end? It just adds unnecessary complexities compared having a separate route with the same handler.

**Comment by mybigman** [comment]
yeh I get you,  can definitely see the downsides.
