### ISSUE TITLE
ability to change middleware order of execution

### ISSUE THREAD

**Issue by mybigman** [bnkamalesh/webgo#46]
ATM the order of the middleware is LIFO which causes to much thinking when adding middlewares, would be nice to be able to change that to FIFO via the webgo config.

**Comment by bnkamalesh** [comment]
@mybigman thank you for the suggestion. This has been irking me since a while as well, I think it's a good feature to have and even make the default behaviour.

**Comment by bnkamalesh** [comment]
#47

**Comment by bnkamalesh** [comment]
This is now implemented in v7.0.0; and is the default behaviour
