### ISSUE TITLE
spelling error

### ISSUE THREAD

**Issue by vasukolli** [bnkamalesh/webgo#5]
Hello,

Thanks for developing this simple framework.
As a non-voice developer I can easily lift up with your framework.
**file** word written as **fil**  in **errors.go** file.

> //C003 Error Code 3
> C003 = "App environment provided in config **fil** Accepted values are `production` or `development`"

-Vasu

**Comment by bnkamalesh** [comment]
Thank you.

**Comment by bnkamalesh** [comment]
Though, I'm not sure how you're using this framework if you're not a developer. I honestly did not even think a non-developer could use this.
